import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SideBar from '@/components/sidebar/SideBar';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ display: 'grid', gridTemplateColumns: 'auto 1fr' }}
        suppressHydrationWarning={true}
      >
        <SideBar />

        <main>{children}</main>
      </body>
    </html>
  );
}
